export const doctorsConsultFormQuestionText = {
  doctorSConsultQ1: "Doctor's Name",
  doctorSConsultQ2: 'Clinical Findings',
  doctorSConsultQ3: "Doctor's Memo",
  doctorSConsultQ4: 'Refer to dietitian?',
  doctorSConsultQ5: 'Reason for Dietitian referral',
  doctorSConsultQ6: 'Refer to Social Support?',
  doctorSConsultQ7: 'Reason for Social Support Rreferral',
  doctorSConsultQ13: 'Refer to Mental Health? (and indicated on Form A)',
  doctorSConsultQ8: 'Refer to Dental?',
  doctorSConsultQ9: 'Reason for Dental referral',
  doctorSConsultQ10: 'Does patient require urgent follow up',
  doctorSConsultQ11: "Completed Doctor's station. Please check that Form A is filled.",
  doctorSConsultQ12: 'Does this patient need a memo to be printed?',
}
