export const FORM_COLLECTION_TO_KEY = {
  registrationForm: 'registration',
  triageForm: 'triage',
  hsgForm: 'hsg',
  cancer365Form: 'cancer365',
  lungFnForm: 'lungFunction',
  wceForm: 'wce',
  gynaeForm: 'gynae',
  podiatryForm: 'podiatry',
  dietitiansConsultForm: 'dietitiansConsult',
  oralHealthForm: 'oralHealth',
  socialServiceForm: 'socialService',
  mentalHealthForm: 'mentalHealth',
  mammobusForm: 'mammobus',
  hpvForm: 'hpv',
  audiometryForm: 'audiometry',
  geriAudiometryForm: 'geriAudiometry',
  vaccineForm: 'vaccine',
  doctorConsultForm: 'doctorConsult',
  summaryForm: 'summary',
  ophthalForm: 'ophthal',
  osteoForm: 'osteo',
  fitForm: 'fit',
  scoliosisForm: 'scoliosis',
  geriEbasDepForm: 'geriEbasDep',
  geriFrailScaleForm: 'geriFrailScale',
  geriParQForm: 'geriParQ',
  geriMmseForm: 'geriMmse',
  geriMMSEForm: 'geriMmse',
  hxPhqForm: 'hxPhq',
  phlebotomyForm: 'phlebotomy',
  phleboForm: 'phlebo',
  geriTugForm: 'geriTug',
  geriVisionForm: 'geriVision',
  hxCancerForm: 'hxCancer',
  nkfForm: 'nkf',
  hxNssForm: 'hxNss',
  hxSocialForm: 'hxSocial',
  hxFamilyForm: 'hxFamily',
  hxHcsrForm: 'hxHcsr',
  hxOralForm: 'hxOral',
  hxScoliosisForm: 'hxScoliosis',
  hxVaccineForm: 'hxVaccine',
  hxM4M5ReviewForm: 'hxM4M5Review',
  hxOsaForm: 'hxOsa',
  geriPhqForm: 'geriPhq',
  geriAmtForm: 'geriAmt',
  geriGraceForm: 'geriGrace',
  geriWhForm: 'geriWh',
  geriInterForm: 'geriInter',
  geriPhysicalActivityLevelForm: 'geriPhysicalActivityLevel',
  geriOtQuestionnaireForm: 'geriOtQuestionnaire',
  geriSppbForm: 'geriSppb',
  geriPtConsultForm: 'geriPtConsult',
  geriOtConsultForm: 'geriOtConsult',
}

export function toFormKey(collectionName) {
  return FORM_COLLECTION_TO_KEY[collectionName] || collectionName
}

export function hasFormKey(collectionName) {
  return Boolean(FORM_COLLECTION_TO_KEY[collectionName])
}
