export const validRegistration = {
  registrationQ1: 'Ms',
  registrationQ2: 'AL',
  registrationQ3: '1980-01-15T00:00:00.000Z',
  registrationQ4: 46,
  registrationQ5: 'Female',
  registrationQ6: 'Chinese 华裔',
  registrationShortAnsQ6: '',
  registrationQ7: 'Singapore Citizen 新加坡公民',
  registrationQ10: '',
  registrationQ11: 'No',
  registrationQ12: 'CHAS Blue',
  registrationQ13: 'None',
  registrationQ16: 'No',
  registrationQ14: 'English',
  registrationQ17: true,
  registrationQ18: 'Yes',
  registrationQ19: 'No',
  registrationQ20: 'Yes',
}

export const validTriage = {
  triageQ1: 140,
  triageQ2: 90,
  triageQHR1: 70,
  triageQ3: 130,
  triageQ4: 80,
  triageQHR2: 80,
  triageQ5: '',
  triageQ6: '',
  triageQHR3: '',
  triageQ7: '',
  triageQ8: '',
  triageQHRAvg: '',
  triageQ9: 'No',
  triageQ10: 165,
  triageQ11: 60,
  triageQ12: '',
  triageQ13: 75,
  triageQ14: 36.8,
  triageQ15: 38,
  triageQ16: 98,
}

export const validHcsr = {
  hxHcsrQ1: 'History Taker',
  hxHcsrQ2: 'NIL',
  hxHcsrQ3: 'No',
  hxHcsrShortAnsQ3: '',
  hxHcsrQ5: 'Yes',
  hxHcsrQ7: 'No',
  hxHcsrShortAnsQ7: '',
  hxhcsrQ8: '',
}
