name: Feature Branch CI

# Trigger:
# - Runs on every push to any non-trunk branch.
# - Purpose: give developers fast feedback on each push before they open a PR.

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md' # Ignore markdown files to avoid unnecessary CI runs for documentation changes

jobs:
  fast-feedback:
    name: Fast Feedback (static)
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'package.json'
          cache: npm

      - name: 3. Install Dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: 4. Lint
        run: npm run lint # no type-checking, as this code is run on js files only, and no usage of ts files in this repo

      - name: 5. Unit Tests
        run: npm run test:ci # complete unit, integration, e2e + data validation checks are WIP by Robin.

      - name: 6. Build Check
        run: npm run build
